### PR TITLE
Added async workers to the backend

### PR DESCRIPTION
**Pull request by YmirKhang**
Changes proposed in this pull request:
-Async workers are introduced to the project
-Info extraction and recommendation system will work async in order to create and update items no matter what
-And when recommendation is on this will be very useful.

Okay installation(Dont forget to run pip install -r requirements.txt):
`sudo apt-get install rabbitmq-server`
`celery -A atlas worker -l info`  
This is the logs of the async workers
celery must be working in the background

@SaitTalhaNisanci  @yigitozkavci

### CODE REVIEW

**Comment by yigitozkavci** [comment]
One part I don't understand: where do we actually define the tasks? We import them from 2 place, but I don't see the definitions

**Comment by YmirKhang** [comment]
@yigitozkavci sorry didnt commit tasks in the initial push :1st_place_medal:

**Comment by yigitozkavci** [comment]
I don't know about the business logic parts, @SaitTalhaNisanci should review those parts I guess. LGTM.

**Review by yigitozkavci — DISMISSED** [review]

**Comment by SaitTalhaNisanci** [comment]
Good job ! We should also do the same thing while editing an item since hidden tags will be extracted there as well in case the description is changed.

**Comment by YmirKhang** [comment]
Added celery kill and restart commands in the Jenkins build configuration

**Pull request closed without merging**
