### PR TITLE
Frontend design

### PR DESCRIPTION
**Pull request by alikaang**
Fixes # .

Changes proposed in this pull request:
- login page rework
- small design fixes

@project_member

### CODE REVIEW

**Comment by alikaang** [comment]
bifor:
whatsapp image 2017-12-06 at 16 24 05
aftır:
whatsapp image 2017-12-06 at 16 24 12

**Comment by alikaang** [comment]
şu güzel prı master hasretinden kurtaralım artık

**Comment by yigitozkavci** [comment]
Oo nice, I'm testing it right now :+1:

**Comment by yigitozkavci** [comment]
I loved the colors and the shadow. Thanks for the nice work!

**Review by yigitozkavci — APPROVED** [review]

**Pull request merged**
