### PR TITLE
Add Nearby Items functionality with all of the components

### PR DESCRIPTION
**Pull request by YmirKhang**
Changes proposed in this pull request:
-Nearby Items page is added
-Google geolocation and item tooltips are added to the map

Screenshot:
image

To-Do:
Styling must be edited,
Card boxes for the map marker tooltips will be implemented

### CODE REVIEW

**Comment by yigitozkavci** [comment]
I am getting this exception right now, fyi @emir350z : 
image

**Comment by YmirKhang** [comment]
@yigitozkavci  I'll check it

**Comment by YmirKhang** [comment]
@yigitozkavci fixed

**Comment by YmirKhang** [comment]
@yigitozkavci  @bounaykut let me know if there are any errors.

**Review by yigitozkavci — APPROVED** [review]

**Pull request merged**
