### PR TITLE
add image_media_item with tests

### LINKED ISSUE #166: Media items
We should have media items in our cultural heritage item model. While adding an media item to a cultural heritage item I can think of 2 choices:
- We can have an endpoint to create a media item and using that endpoint client will create a media item and put its **id** or **ids**, if there are more than one media items, to the field 'media_items' in json.
- Or instead of having a separate endpoint for media items client can directly give the related information to  cultural heritage item's 'media_items' field. 

Which one do you guys think is better ?

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
fixes #166 
Image media item model is added and adding images to cultural heritage items is implemented. 
The endpoint to add an image to a cultural heritage item is as follow:
```POST /cultural_heritage_item/id/image```
image model has the following fields that you can fill:

- Url

I think we should also add the starting point, something like 'top left point' to the model for future usage.

Now you can get the images of specific cultural heritage item with the following request:

```GET /cultural_heritage_item/id```
and the response will have a field '**images**' which is a list that has all the images for the cultural heritage item that has **id**

### CODE REVIEW

**Comment by yigitozkavci** [comment]
Actually, I don't think we should keep width and height information associated with any of the images. We should assume nothing for the image's dimensions while designing the client-side. What do you think for mobile side @eozd ?

**Comment by SaitTalhaNisanci** [comment]
I think for future usage width and height can be useful in front end. Why dont you think so @yigitozkavci ?

**Comment by yigitozkavci** [comment]
Users can upload images with variety of width and height, hence both frontend and mobile should make their designs regardless of image's width or height anyway. I thought it's strange because I've never seen image sizes being saved in database. If also @eozd won't make use of it, let's not keep that data in database

**Comment by SaitTalhaNisanci** [comment]
I talked to @eozd. I removed those fields from the model @yigitozkavci .

**Review by yigitozkavci — APPROVED** [review]

**Pull request merged**
