### PR TITLE
added retrieval for an item

### PR DESCRIPTION
**Pull request by ramazankani**
please review my changes

### CODE REVIEW

**Review by YmirKhang — APPROVED** [review]
Nice

**Comment by buseece** [comment]
Don't we need annotations too? Is it forgotten or do you have another idea about it? @ramazankani @emir350z

**Comment by YmirKhang** [comment]
Yeah we still need it, but we aren't going to implement any API for the annotations so we just leave it to the project development phase @buseece

**Review by yigitozkavci — APPROVED** [review]

**Review by buseece — COMMENTED** [review]
I think we need to add annotation part since it is a helper API for our project but we have a limited time for now, and if everyone is agreed on merging it, I also approve

**Pull request merged**
