### PR TITLE
Fix compile error observed at rev b465

### PR DESCRIPTION
**Pull request by egemahlec**

### CODE REVIEW

**Comment by yigitozkavci** [comment]
@egem Could you explain this fix? Those getters and setters on CulturalHeritage are necessary imo, what do you think @emir350z ?

**Comment by bounaykut** [comment]
I think, they are needed in updating a cultural heritage item.

**Comment by egemahlec** [comment]
I am agree that we have to write these methods however we need to write one method for every get and set operation. There were two methods which are doing same operation with same name. Therefore, I faced with compile error.

**Comment by egemahlec** [comment]
Could you also please try to compile the latest revision of master branch?

**Comment by yigitozkavci** [comment]
Wow, I did not notice this one. Thanks, merging right away.

**Comment by yigitozkavci** [comment]
Also: your branch is compiling well right now.

**Pull request merged**
