### PR TITLE
Check travis tests for backend/frontend/android.

### PR DESCRIPTION
**Pull request by eozd**
I have created three python test scripts that should test the folder it is in, e.g. backend. I couldn't find a way to tell to Travis that we have multiple languages and environments in our project. Maybe for now we can call the main testing procedure from these python scripts and simply forward the error code returned from those routines.

### CODE REVIEW

**Comment by eozd** [comment]
We might also need to do research on how to run tests for one part of the project, e.g. android. We shouldn't need to run all backend,frontend tests again for unrelated changes. We can continue the related discussion in #169.

**Comment by yigitozkavci** [comment]
I don't think not running every test on every PR should be a high-priority consideration, at least for now. Shall I add backend test script to `Atlas/backend/test`?

**Comment by eozd** [comment]
It would be better if we call the tests from ```backend/test``` file. That way tests related to certain parts would remain in those parts. Though I am not sure how to handle dependencies, databases, etc. with Travis especially since backend frontend and android have different envs. and deps.

**Comment by eozd** [comment]
Finally, I have managed to make JUnits run and pass on Travis servers. You can configure frontend and backend parts.

**Review by yigitozkavci — APPROVED** [review]

**Pull request merged**
