### PR TITLE
Small refactor on frontend

### PR DESCRIPTION
**Pull request by yigitozkavci**

### CODE REVIEW

**Review by YmirKhang — APPROVED** [review]
That compile warnings :D

**Review by SaitTalhaNisanci — APPROVED** [review]

**Comment by yigitozkavci** [comment]
@emir350z Have you tested your redirect code? It practically does nothing when I tested in my local.

**Comment by yigitozkavci** [comment]
In fact, that line causes an exception. Reverting it, fyi @emir350z

**Comment by yigitozkavci** [comment]
@emir350z I think you meant to fetch user info after successful signup, am I right? This line causes exception though: https://github.com/bounswe/bounswe2017group10/pull/205/files#diff-e0420a4a36365d28528431cd0917d047R43

**Pull request merged**
